export const apiEndpoints = {
  auth: {
    login: "/api/auth/login",
    register: "/api/auth/register",
    refreshToken: "/api/auth/refresh",
    forgotPassword: "/api/auth/forgot-password",
    resetPassword: "/api/auth/reset-password",
    changePassword: "/api/auth/change-password",
    logout: "/api/auth/logout",
    logoutAll: "/api/auth/logout-all",
    getCurrentUser: "/api/auth/me",
    confirmEmail: "/api/auth/confirm-email",
  },
  lookups: {
    all: "/api/lookups",
    products: "/api/lookups/products",
    categories: "/api/lookups/categories",
    warehouses: "/api/lookups/warehouses",
    suppliers: "/api/lookups/suppliers",
    priceLists: "/api/lookups/price-lists",
    unitDefinitions: "/api/lookups/unit-definitions",
    regions: "/api/lookups/regions",
  },
  unitDefinitions: {
    list: "/api/unit-definitions",
    byId: (id: string) => `/api/unit-definitions/${id}`,
  },
  regions: {
    list: "/api/regions",
    byId: (id: string) => `/api/regions/${id}`,
  },
  identity: {
    users: "/api/users",
    userById: (id: string) => `/api/users/${id}`,
    resendInvitation: (id: string) => `/api/users/${id}/resend-invitation`,
    roles: "/api/roles",
    roleById: (id: string) => `/api/roles/${id}`,
    permissionCatalog: "/api/roles/permissions/catalog",
  },
  system: {
    settings: "/api/system-settings",
    integrations: "/api/integrations",
    integrationById: (id: string) => `/api/integrations/${id}`,
    integrationTest: (id: string) => `/api/integrations/${id}/test`,
  },
  products: {
    list: "/api/products",
    byId: (id: string) => `/api/products/${id}`,
    detail: (id: string) => `/api/products/${id}/detail`,
    full: "/api/products/full",
    fullById: (id: string) => `/api/products/${id}/full`,
    categoryMaps: (id: string) => `/api/products/${id}/category-maps`,
    modules: (id: string) => `/api/products/${id}/modules`,
    moduleById: (productId: string, moduleId: string) => `/api/products/${productId}/modules/${moduleId}`,
    pricingTiers: (id: string) => `/api/products/${id}/pricing-tiers`,
    pricingTierById: (productId: string, tierId: string) => `/api/products/${productId}/pricing-tiers/${tierId}`,
    pricingRules: (id: string) => `/api/products/${id}/pricing-rules`,
    pricingRuleById: (pricingRuleId: string) => `/api/products/pricing-rules/${pricingRuleId}`,
    reorderPricingRules: (id: string) => `/api/products/${id}/pricing-rules/reorder`,
    regions: (productId: string) => `/api/products/${productId}/regions`,
    regionById: (productRegionId: string) => `/api/products/regions/${productRegionId}`,
    productUnits: (productId: string) => `/api/products/${productId}/units`,
    productUnitById: (productUnitId: string) => `/api/products/units/${productUnitId}`,
    licenseOfferings: (id: string) => `/api/products/${id}/license-offerings`,
    licenseOfferingById: (productId: string, offeringId: string) => `/api/products/${productId}/license-offerings/${offeringId}`,
    unitConversions: (productId: string) => `/api/products/${productId}/unit-conversions`,
    unitConversionById: (productId: string, conversionId: string) => `/api/products/${productId}/unit-conversions/${conversionId}`,
    moduleOfferingPrices: (productId: string, moduleId: string) => `/api/products/${productId}/modules/${moduleId}/offering-prices`,
    moduleOfferingPriceById: (productId: string, moduleId: string, priceId: string) => `/api/products/${productId}/modules/${moduleId}/offering-prices/${priceId}`,
  },
  attributes: {
    list: "/api/attributes",
    byId: (id: string) => `/api/attributes/${id}`,
  },
  catalog: {
    categories: "/api/catalog/categories",
    categoryById: (id: string) => `/api/catalog/categories/${id}`,
    suppliers: "/api/catalog/suppliers",
    supplierById: (id: string) => `/api/catalog/suppliers/${id}`,
    warehouses: "/api/catalog/warehouses",
    warehouseById: (id: string) => `/api/catalog/warehouses/${id}`,
  },
  inventory: {
    inventories: "/api/inventory/inventories",
    inventoryById: (id: string) => `/api/inventory/inventories/${id}`,
    transactions: "/api/inventory/transactions",
    reservations: "/api/inventory/reservations",
    reservationById: (id: string) => `/api/inventory/reservations/${id}`,
    reservationStatus: (id: string) => `/api/inventory/reservations/${id}/status`,
  },
  priceLists: {
    list: "/api/pricelists",
    byId: (id: string) => `/api/pricelists/${id}`,
    items: "/api/pricelists/items",
    itemsByPriceListId: (id: string) => `/api/pricelists/${id}/items`,
    itemById: (id: string) => `/api/pricelists/items/${id}`,
  },
} as const;
