export const apiEndpoints = {
  auth: {
    login: "/api/auth/login",
    register: "/api/auth/register",
    refreshToken: "/api/auth/refresh",
    forgotPassword: "/api/auth/forgot-password",
    resetPassword: "/api/auth/reset-password",
    changePassword: "/api/auth/change-password",
    logout: "/api/auth/logout",
    logoutAll: "/api/auth/logout-all",
    getCurrentUser: "/api/auth/me",
    confirmEmail: "/api/auth/confirm-email",
  },
  lookups: {
    all: "/api/lookups",
    products: "/api/lookups/products",
    categories: "/api/lookups/categories",
    warehouses: "/api/lookups/warehouses",
    suppliers: "/api/lookups/suppliers",
    priceLists: "/api/lookups/price-lists",
    unitDefinitions: "/api/lookups/unit-definitions",
  },
  unitDefinitions: {
    list: "/api/unit-definitions",
    byId: (id: string) => `/api/unit-definitions/${id}`,
  },
  products: {
    list: "/api/products",
    byId: (id: string) => `/api/products/${id}`,
    detail: (id: string) => `/api/products/${id}/detail`,
    full: "/api/products/full",
    fullById: (id: string) => `/api/products/${id}/full`,
    categoryMaps: (id: string) => `/api/products/${id}/category-maps`,
    modules: (id: string) => `/api/products/${id}/modules`,
    moduleById: (productId: string, moduleId: string) => `/api/products/${productId}/modules/${moduleId}`,
    pricingTiers: (id: string) => `/api/products/${id}/pricing-tiers`,
    pricingTierById: (productId: string, tierId: string) => `/api/products/${productId}/pricing-tiers/${tierId}`,
    licenseOfferings: (id: string) => `/api/products/${id}/license-offerings`,
    licenseOfferingById: (productId: string, offeringId: string) => `/api/products/${productId}/license-offerings/${offeringId}`,
    unitConversions: (productId: string) => `/api/products/${productId}/unit-conversions`,
    unitConversionById: (productId: string, conversionId: string) => `/api/products/${productId}/unit-conversions/${conversionId}`,
    moduleOfferingPrices: (productId: string, moduleId: string) => `/api/products/${productId}/modules/${moduleId}/offering-prices`,
    moduleOfferingPriceById: (productId: string, moduleId: string, priceId: string) => `/api/products/${productId}/modules/${moduleId}/offering-prices/${priceId}`,
  },
  attributes: {
    list: "/api/attributes",
    byId: (id: string) => `/api/attributes/${id}`,
  },
  catalog: {
    categories: "/api/catalog/categories",
    categoryById: (id: string) => `/api/catalog/categories/${id}`,
    suppliers: "/api/catalog/suppliers",
    supplierById: (id: string) => `/api/catalog/suppliers/${id}`,
    warehouses: "/api/catalog/warehouses",
    warehouseById: (id: string) => `/api/catalog/warehouses/${id}`,
  },
  inventory: {
    inventories: "/api/inventory/inventories",
    inventoryById: (id: string) => `/api/inventory/inventories/${id}`,
    transactions: "/api/inventory/transactions",
    reservations: "/api/inventory/reservations",
    reservationById: (id: string) => `/api/inventory/reservations/${id}`,
    reservationStatus: (id: string) => `/api/inventory/reservations/${id}/status`,
  },
  priceLists: {
    list: "/api/pricelists",
    byId: (id: string) => `/api/pricelists/${id}`,
    items: "/api/pricelists/items",
    itemsByPriceListId: (id: string) => `/api/pricelists/${id}/items`,
    itemById: (id: string) => `/api/pricelists/items/${id}`,
  },
} as const;
