export const apiEndpoints = {
  auth: {
    login: "/api/auth/login",
    register: "/api/auth/register",
    refreshToken: "/api/auth/refresh",
    forgotPassword: "/api/auth/forgot-password",
    resetPassword: "/api/auth/reset-password",
    changePassword: "/api/auth/change-password",
    logout: "/api/auth/logout",
    logoutAll: "/api/auth/logout-all",
    getCurrentUser: "/api/auth/me",
    confirmEmail: "/api/auth/confirm-email",
  },
  lookups: {
    all: "/api/lookups",
    products: "/api/lookups/products",
    categories: "/api/lookups/categories",
    warehouses: "/api/lookups/warehouses",
    suppliers: "/api/lookups/suppliers",
    priceLists: "/api/lookups/price-lists",
  },
  products: {
    list: "/api/products",
    byId: (id: string) => `/api/products/${id}`,
    detail: (id: string) => `/api/products/${id}/detail`,
    full: "/api/products/full",
    fullById: (id: string) => `/api/products/${id}/full`,
    categoryMaps: (id: string) => `/api/products/${id}/category-maps`,
  },
  attributes: {
    list: "/api/attributes",
    byId: (id: string) => `/api/attributes/${id}`,
  },
  catalog: {
    categories: "/api/catalog/categories",
    categoryById: (id: string) => `/api/catalog/categories/${id}`,
    suppliers: "/api/catalog/suppliers",
    supplierById: (id: string) => `/api/catalog/suppliers/${id}`,
    warehouses: "/api/catalog/warehouses",
    warehouseById: (id: string) => `/api/catalog/warehouses/${id}`,
  },
  inventory: {
    inventories: "/api/inventory/inventories",
    inventoryById: (id: string) => `/api/inventory/inventories/${id}`,
    transactions: "/api/inventory/transactions",
    reservations: "/api/inventory/reservations",
    reservationById: (id: string) => `/api/inventory/reservations/${id}`,
    reservationStatus: (id: string) => `/api/inventory/reservations/${id}/status`,
  },
  priceLists: {
    list: "/api/pricelists",
    byId: (id: string) => `/api/pricelists/${id}`,
    items: "/api/pricelists/items",
    itemsByPriceListId: (id: string) => `/api/pricelists/${id}/items`,
    itemById: (id: string) => `/api/pricelists/items/${id}`,
  },
} as const;
